# Generated by Django 3.2.5 on 2021-08-11 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sinonimia', models.CharField(max_length=220)),
                ('genero', models.CharField(max_length=220)),
                ('epiteto', models.CharField(max_length=220)),
                ('familia', models.CharField(max_length=220)),
                ('link_flora', models.CharField(max_length=220)),
                ('ativa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Espécie',
                'verbose_name_plural': 'Espécies',
                'ordering': ['sinonimia'],
            },
        ),
        migrations.CreateModel(
            name='InfoReproducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flor', models.CharField(max_length=220)),
                ('info_flor', models.TextField()),
                ('fruto', models.CharField(max_length=220)),
                ('info_fruto', models.CharField(max_length=220)),
                ('antese', models.CharField(max_length=220)),
                ('tipo_reproducao', models.CharField(choices=[('ND', 'Não Definido'), ('AUTO', 'Autogamia'), ('XENO', 'Xenogamia'), ('HERCO', 'Hercogamia')], default='ND', max_length=6)),
                ('recursos_oferecidos', models.TextField()),
                ('semente', models.CharField(max_length=220)),
                ('info_semente', models.TextField()),
                ('info_botanica', models.TextField()),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epifitas.especie')),
            ],
            options={
                'verbose_name': 'Informação Reprodutiva',
                'verbose_name_plural': 'Informações Reprodutivas',
                'ordering': ['especie'],
            },
        ),
        migrations.CreateModel(
            name='InfoGeografica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_registros', models.IntegerField()),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epifitas.especie')),
            ],
            options={
                'verbose_name': 'Informação Geográfica',
                'verbose_name_plural': 'Informações Geográficas',
                'ordering': ['especie'],
            },
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planta', models.ImageField(blank=True, null=True, upload_to='plantas/')),
                ('fruto', models.ImageField(blank=True, null=True, upload_to='frutos/')),
                ('flor', models.ImageField(blank=True, null=True, upload_to='flores/')),
                ('folha', models.ImageField(blank=True, null=True, upload_to='folhas/')),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epifitas.especie')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
