# Generated by Django 3.2.5 on 2021-07-09 15:01

from django.db import migrations, models
import django.db.models.deletion
import epifitas.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sinonimia', models.CharField(db_index=True, max_length=220)),
                ('genero', models.CharField(db_index=True, max_length=220)),
                ('epiteto', models.CharField(db_index=True, max_length=220)),
                ('familia', models.CharField(db_index=True, max_length=220)),
                ('link_flora', models.CharField(blank=True, max_length=220)),
                ('ativa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Espécie',
                'verbose_name_plural': 'Espécies',
                'ordering': ['sinonimia'],
            },
        ),
        migrations.CreateModel(
            name='InfoReproducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flor', models.CharField(max_length=220)),
                ('info_flor', models.TextField()),
                ('fruto', models.CharField(max_length=220)),
                ('info_fruto', models.CharField(max_length=220)),
                ('antese', models.CharField(max_length=220)),
                ('tipo_reproducao', models.CharField(choices=[('ND', 'Não Definido'), ('AUTO', 'Autogamia'), ('XENO', 'Xenogamia'), ('HERCO', 'Hercogamia')], default='ND', max_length=6)),
                ('recursos_oferecidos', models.TextField()),
                ('semente', models.CharField(max_length=220)),
                ('info_semente', models.TextField()),
                ('info_botanica', models.TextField()),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epifitas.especie')),
            ],
            options={
                'verbose_name': 'Informação Reprodutiva',
                'verbose_name_plural': 'Informações Reprodutivas',
                'ordering': ['especie'],
            },
        ),
        migrations.CreateModel(
            name='InfoGeografica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_registros', models.IntegerField(db_index=True)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epifitas.especie')),
            ],
            options={
                'verbose_name': 'Informação Geográfica',
                'verbose_name_plural': 'Informações Geográficas',
                'ordering': ['especie'],
            },
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planta', models.FileField(blank=True, db_index=True, upload_to=epifitas.models.Foto.dir_planta)),
                ('fruto', models.FileField(blank=True, db_index=True, upload_to=epifitas.models.Foto.dir_fruto)),
                ('flor', models.FileField(blank=True, db_index=True, upload_to=epifitas.models.Foto.dir_flor)),
                ('folha', models.FileField(blank=True, db_index=True, upload_to=epifitas.models.Foto.dir_folha)),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epifitas.especie')),
            ],
        ),
    ]
