# Generated by Django 3.2.4 on 2021-07-01 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epifitas', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuario',
            new_name='Contribuidor',
        ),
    ]
