# Generated by Django 3.2.4 on 2021-07-01 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epifitas', '0001_initial'),
        ('usuarios', '0002_rename_usuario_contribuidor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contribuidor',
            new_name='Usuario',
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['nome'], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
    ]
